---
title: "Sobre mi"
---

## Sobre mi

Mi nombre es Andrés Felipe Cabrera Angulo, nací el 8 de julio de 1998 en la cuidad de Bogotá, Colombia.
Mi madre es Luz Marina Angulo y mi padre es Nelson Cabrera Lozano, mi madre es psicologa graduada de la universidad luis amigo, y pensionada de prestar servicios en el INPEC, la información acerca de mi padre es desconocida debido a que no estuvo durante mi etapa de crecimiento. Tengo un hermano menor llamado Emmanuel Perez Angulo y posee 12 años de edad.

Aunque mi nacimiento sucediera en la ciudad de Bogotá, mi núcleo familiar se trasladó a la ciudad de Medellin a los dos meses posteriores a mi nacimiento, desde ese momento el lapso de tiempo hasta la actualidad he vivido en el municipio de Bello, exactamente en el barrio las Vegas.

El desarrollo de mi actividad academica sucedió en la institución educativa Nazaret donde cursé todos los niveles de aprendizaje desde primero de primaria hasta el grado 11 de bachillerato, durante este proceso fui seleccionado en el cuadro de honor en algunas ocaciones, participe en el grupo musical y fui miembro del comite de organización del personero estudiantil.

En el aspecto de educación superior, soy un estudiante de la Universidad Nacional de Colombia desde el año 2015, de la carrera de estadistica.

En cuanto a mis cualidades poseo un manejo intermedio de intrumentos como guitarra(acustica y electrica), tengo un manejo de tecnica y conocimientos basicos para deportes como futbol, baloncesto, volleyball, tenis de mesa y natación.Me considero una persona de caracter determinante con un toque de maleabilidad,ademas de ser una persona paciente y tranquila. 